name: Windows bug
description: Create a Windows-specific bug report
labels:
  - B - bug
  - DS - windows
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the problem you're having
    validations:
      required: true
  - type: textarea
    id: os-version
    attributes:
      label: Windows version
      description: What version of Windows are you using? Please paste in the output of the `ver` command.
      placeholder: |
        Microsoft Windows [Version 10.0.19042.2251]
      render: shell
    validations:
      required: true
  - type: textarea
    id: winit-version
    attributes:
      label: Winit version
      description: What version of Winit are you using?
      placeholder: 0.29.11
    validations:
      required: true
