fn main() {
    windows::build!(
        Windows::Win32::Devices::HumanInterfaceDevice::MOUSE_MOVE_RELATIVE,
        Windows::Win32::Globalization::{
            ImmGetContext, ImmReleaseContext, ImmSetCompositionWindow, CFS_POINT,
        },
        Windows::Win32::Graphics::Dwm::{
            DwmEnableBlurBehindWindow, DWM_BB_BLURREGION, DWM_BB_ENABLE, DWM_BLURBEHIND,
        },
        Windows::Win32::Graphics::Gdi::{
            ChangeDisplaySettingsExW, ClientToScreen, CreateRectRgn, DeleteObject, EnumDisplayMonitors,
            EnumDisplaySettingsExW, GetDC, GetDeviceCaps, GetMonitorInfoW, GetUpdateRect,
            InvalidateRgn, MonitorFromPoint, MonitorFromRect, MonitorFromWindow, RedrawWindow,
            ScreenToClient, ValidateRect, CDS_FULLSCREEN, CDS_TYPE, DISP_CHANGE, DISP_CHANGE_BADFLAGS,
            DISP_CHANGE_BADMODE, DISP_CHANGE_BADPARAM, DISP_CHANGE_FAILED, DISP_CHANGE_SUCCESSFUL,
            DM_BITSPERPEL, DM_DISPLAYFREQUENCY, DM_PELSHEIGHT, DM_PELSWIDTH, LOGPIXELSX,
            MONITORINFOEXW, MONITOR_DEFAULTTONEAREST, MONITOR_DEFAULTTONULL, MONITOR_DEFAULTTOPRIMARY,
            RDW_INTERNALPAINT, REDRAW_WINDOW_FLAGS,
        },
        Windows::Win32::System::Com::{
            CoCreateInstance, CoInitializeEx, CoUninitialize, OleInitialize, RegisterDragDrop,
            RevokeDragDrop, CLSCTX_ALL, COINIT_APARTMENTTHREADED,
        },
        Windows::Win32::System::Diagnostics::Debug::{
            FlashWindowEx, FLASHWINFO, FLASHW_ALL, FLASHW_STOP, FLASHW_TIMERNOFG, FLASHW_TRAY,
        },
        Windows::Win32::System::SystemServices::{
            GetModuleHandleW, GetProcAddress, LoadLibraryA, MsgWaitForMultipleObjectsEx,
            DPI_AWARENESS_CONTEXT, DPI_AWARENESS_CONTEXT, HINSTANCE, MWMO_INPUTAVAILABLE,
            OLE_E_WRONGCOMPOBJ, PSTR, PWSTR, RPC_E_CHANGED_MODE, VER_EQUAL, VER_GREATER_EQUAL,
        },
        Windows::Win32::System::Threading::{GetCurrentThreadId, WAIT_TIMEOUT},
        Windows::Win32::System::WindowsProgramming::{
            VerSetConditionMask, VerifyVersionInfoW, INFINITE, VER_BUILDNUMBER, VER_MAJORVERSION,
            VER_MINORVERSION,
        },
        Windows::Win32::UI::Accessibility::{HCF_HIGHCONTRASTON, HIGHCONTRASTA},
        Windows::Win32::UI::Controls::{
            SetWindowTheme, HOVER_DEFAULT, LR_DEFAULTSIZE, LR_LOADFROMFILE, WM_MOUSELEAVE,
        },
        Windows::Win32::UI::DisplayDevices::POINTS,
        Windows::Win32::UI::HiDpi::{
            AdjustWindowRectExForDpi, GetDpiForWindow, MDT_EFFECTIVE_DPI, MONITOR_DPI_TYPE,
            PROCESS_DPI_AWARENESS, PROCESS_PER_MONITOR_DPI_AWARE,
        },
        Windows::Win32::UI::KeyboardAndMouseInput::{
            EnableWindow, GetActiveWindow, GetKeyState, GetKeyboardLayout, GetKeyboardState,
            GetRawInputData, GetRawInputDeviceInfoW, GetRawInputDeviceList, MapVirtualKeyA,
            MapVirtualKeyW, RegisterRawInputDevices, ReleaseCapture, ReleaseCapture, SendInput,
            SetCapture, ToUnicodeEx, TrackMouseEvent, INPUT_KEYBOARD, INPUT_TYPE, KEYBD_EVENT_FLAGS,
            KEYEVENTF_EXTENDEDKEY, KEYEVENTF_KEYUP, RAWINPUT, RAWINPUTDEVICELIST, RIDEV_DEVNOTIFY,
            RIDEV_INPUTSINK, RIDI_DEVICEINFO, RIDI_DEVICENAME, RID_DEVICE_INFO, RID_DEVICE_INFO_HID,
            RID_DEVICE_INFO_KEYBOARD, RID_DEVICE_INFO_MOUSE, RID_INPUT, RIM_TYPEHID, RIM_TYPEKEYBOARD,
            RIM_TYPEKEYBOARD, RIM_TYPEMOUSE, TME_LEAVE,
        },
        Windows::Win32::UI::MenusAndResources::HMENU,
        Windows::Win32::UI::PointerInput::{
            POINTER_FLAG_DOWN, POINTER_FLAG_UP, POINTER_FLAG_UPDATE, POINTER_INFO, POINTER_PEN_INFO,
            POINTER_TOUCH_INFO,
        },
        Windows::Win32::UI::Shell::{
            DefSubclassProc, ITaskbarList2, RemoveWindowSubclass, SetWindowSubclass, TaskbarList,
        },
        Windows::Win32::UI::TouchInput::{
            CloseTouchInputHandle, GetTouchInputInfo, RegisterTouchWindow, HTOUCHINPUT,
            TOUCHEVENTF_DOWN, TOUCHEVENTF_MOVE, TOUCHEVENTF_UP, TWF_WANTPALM,
        },
        Windows::Win32::UI::WindowsAndMessaging::{
            AdjustWindowRectEx, ClipCursor, CreateIcon, CreateWindowExW, DefWindowProcW, DestroyIcon,
            DestroyWindow, DispatchMessageW, GetClientRect, GetClipCursor, GetCursorPos, GetMenu,
            GetMessageW, GetSystemMetrics, GetWindowLongPtrW, GetWindowLongW, GetWindowPlacement,
            GetWindowRect, IsProcessDPIAware, LoadCursorW, LoadImageW, PeekMessageW, PostMessageW,
            PostThreadMessageW, RegisterClassExW, RegisterWindowMessageA, SendMessageW, SetCursor,
            SetCursorPos, SetForegroundWindow, SetWindowLongPtrW, SetWindowLongW, SetWindowPlacement,
            SetWindowPos, SetWindowTextW, ShowCursor, ShowWindow, SystemParametersInfoA,
            TranslateMessage, CS_HREDRAW, CS_OWNDC, CS_VREDRAW, CW_USEDEFAULT, GIDC_ARRIVAL,
            GIDC_REMOVAL, GWLP_HINSTANCE, GWL_EXSTYLE, GWL_STYLE, HTCAPTION, HTCLIENT, HWND_NOTOPMOST,
            HWND_TOPMOST, ICON_BIG, ICON_SMALL, IDC_APPSTARTING, IDC_ARROW, IDC_CROSS, IDC_HAND,
            IDC_HELP, IDC_IBEAM, IDC_NO, IDC_SIZEALL, IDC_SIZENESW, IDC_SIZENS, IDC_SIZENWSE,
            IDC_SIZEWE, IDC_WAIT, IMAGE_ICON, MAPVK_VK_TO_CHAR, MAPVK_VK_TO_VSC, MAPVK_VSC_TO_VK_EX,
            MINMAXINFO, NID_READY, PM_NOREMOVE, PM_QS_PAINT, PM_REMOVE, PT_PEN, PT_TOUCH, QS_ALLEVENTS,
            RI_KEY_E0, RI_KEY_E1, RI_MOUSE_LEFT_BUTTON_DOWN, RI_MOUSE_LEFT_BUTTON_UP,
            RI_MOUSE_MIDDLE_BUTTON_DOWN, RI_MOUSE_MIDDLE_BUTTON_UP, RI_MOUSE_RIGHT_BUTTON_DOWN,
            RI_MOUSE_RIGHT_BUTTON_UP, RI_MOUSE_WHEEL, SC_MINIMIZE, SC_RESTORE, SC_SCREENSAVE,
            SET_WINDOW_POS_FLAGS, SIZE_MAXIMIZED, SM_CXVIRTUALSCREEN, SM_CYVIRTUALSCREEN, SM_DIGITIZER,
            SM_IMMENABLED, SM_XVIRTUALSCREEN, SM_YVIRTUALSCREEN, SPI_GETHIGHCONTRAST,
            SWP_ASYNCWINDOWPOS, SWP_ASYNCWINDOWPOS, SWP_FRAMECHANGED, SWP_NOACTIVATE, SWP_NOACTIVATE,
            SWP_NOMOVE, SWP_NOREPOSITION, SWP_NOSIZE, SWP_NOSIZE, SWP_NOZORDER, SW_HIDE, SW_MAXIMIZE,
            SW_MINIMIZE, SW_RESTORE, SW_SHOW, SYSTEM_METRICS_INDEX, VK_ADD, VK_APPS, VK_BACK,
            VK_BROWSER_BACK, VK_BROWSER_FAVORITES, VK_BROWSER_FORWARD, VK_BROWSER_HOME,
            VK_BROWSER_REFRESH, VK_BROWSER_SEARCH, VK_BROWSER_STOP, VK_CAPITAL, VK_CONTROL, VK_CONVERT,
            VK_DECIMAL, VK_DELETE, VK_DIVIDE, VK_DOWN, VK_END, VK_ESCAPE, VK_F1, VK_F10, VK_F11,
            VK_F12, VK_F13, VK_F14, VK_F15, VK_F16, VK_F17, VK_F18, VK_F19, VK_F2, VK_F20, VK_F21,
            VK_F22, VK_F23, VK_F24, VK_F3, VK_F4, VK_F5, VK_F6, VK_F7, VK_F8, VK_F9, VK_HOME,
            VK_INSERT, VK_KANA, VK_KANJI, VK_LAUNCH_MAIL, VK_LAUNCH_MEDIA_SELECT, VK_LCONTROL, VK_LEFT,
            VK_LMENU, VK_LMENU, VK_LSHIFT, VK_LWIN, VK_LWIN, VK_MEDIA_NEXT_TRACK, VK_MEDIA_PLAY_PAUSE,
            VK_MEDIA_PREV_TRACK, VK_MEDIA_STOP, VK_MENU, VK_MENU, VK_MULTIPLY, VK_NEXT, VK_NONCONVERT,
            VK_NUMLOCK, VK_NUMPAD0, VK_NUMPAD1, VK_NUMPAD2, VK_NUMPAD3, VK_NUMPAD4, VK_NUMPAD5,
            VK_NUMPAD6, VK_NUMPAD7, VK_NUMPAD8, VK_NUMPAD9, VK_OEM_1, VK_OEM_102, VK_OEM_2, VK_OEM_3,
            VK_OEM_4, VK_OEM_5, VK_OEM_6, VK_OEM_7, VK_OEM_COMMA, VK_OEM_MINUS, VK_OEM_PERIOD,
            VK_OEM_PLUS, VK_PAUSE, VK_PRIOR, VK_RCONTROL, VK_RETURN, VK_RIGHT, VK_RMENU, VK_RSHIFT,
            VK_RWIN, VK_RWIN, VK_SCROLL, VK_SHIFT, VK_SLEEP, VK_SNAPSHOT, VK_SPACE, VK_SUBTRACT,
            VK_TAB, VK_UP, VK_VOLUME_DOWN, VK_VOLUME_MUTE, VK_VOLUME_UP, WHEEL_DELTA, WINDOWPOS,
            WINDOW_EX_STYLE, WINDOW_LONG_PTR_INDEX, WINDOW_STYLE, WM_CAPTURECHANGED, WM_CHAR, WM_CLOSE,
            WM_DESTROY, WM_DPICHANGED, WM_DROPFILES, WM_ENTERSIZEMOVE, WM_EXITSIZEMOVE,
            WM_GETMINMAXINFO, WM_INPUT, WM_INPUT_DEVICE_CHANGE, WM_KEYDOWN, WM_KEYDOWN, WM_KEYUP,
            WM_KEYUP, WM_KILLFOCUS, WM_LBUTTONDOWN, WM_LBUTTONUP, WM_MBUTTONDOWN, WM_MBUTTONUP,
            WM_MOUSEHWHEEL, WM_MOUSEMOVE, WM_MOUSEMOVE, WM_MOUSEWHEEL, WM_NCCREATE, WM_NCDESTROY,
            WM_NCDESTROY, WM_NCLBUTTONDOWN, WM_NCLBUTTONDOWN, WM_PAINT, WM_PAINT, WM_PAINT, WM_PAINT,
            WM_PAINT, WM_POINTERDOWN, WM_POINTERUP, WM_POINTERUPDATE, WM_RBUTTONDOWN, WM_RBUTTONUP,
            WM_SETCURSOR, WM_SETFOCUS, WM_SETICON, WM_SIZE, WM_SYSCHAR, WM_SYSCOMMAND, WM_SYSKEYDOWN,
            WM_SYSKEYDOWN, WM_SYSKEYDOWN, WM_SYSKEYUP, WM_SYSKEYUP, WM_TOUCH, WM_WINDOWPOSCHANGED,
            WM_WINDOWPOSCHANGING, WM_WININICHANGE, WM_XBUTTONDOWN, WM_XBUTTONUP, WNDCLASSEXW,
            WNDCLASS_STYLES, WS_BORDER, WS_CAPTION, WS_CHILD, WS_CLIPCHILDREN, WS_CLIPSIBLINGS,
            WS_EX_ACCEPTFILES, WS_EX_APPWINDOW, WS_EX_LAYERED, WS_EX_NOACTIVATE,
            WS_EX_NOREDIRECTIONBITMAP, WS_EX_TOPMOST, WS_EX_TRANSPARENT, WS_EX_WINDOWEDGE, WS_MAXIMIZE,
            WS_MAXIMIZEBOX, WS_MINIMIZE, WS_MINIMIZEBOX, WS_OVERLAPPEDWINDOW, WS_POPUP, WS_POPUP,
            WS_SIZEBOX, WS_SYSMENU, WS_VISIBLE,
        },
    );
}
